### ISSUE TITLE
Friends we made along the way- DJCAD Make

### ISSUE THREAD

**Issue by Saallen** [openiotstudio/general#2]
Rob Jackson and Ali Napier, [DJCADMake](https://sites.dundee.ac.uk/djcadmake/)

We operate the Make Space at Duncan of Jordanstone College of Art and Design (DJCAD) ,
University of Dundee. We set up the facility in the summer of 2014, after a long period
during which it had become clear that there was a need for a workshop which offered
equipment and in-house expertise focussed on creating objects, products and pieces of art
digitally.
We provide support for 1100 students, faculty staff and researchers within the College, as
well as opening avenues for collaboration across the wider University.
Laser cutting/etching, 3D printing/scanning/modelling and electronics make up the vast
majority of our work – in addition we provide access to CNC milling equipment, a large-
format vinyl cutter and sublimation printing.

We’re so happy to welcome our friends at Mozilla and the Scotland IoT Design Sprint
attendees to our space.

Rob Jackson is from Ireland. He studied Fine Art Printmaking at NCAD, Dublin followed by a
Masters at DJCAD. Rob then worked at DCA Print Studio where he developed his interest in
integrating traditional practice and digital making. He joined DJCAD when the space opened
in September 2014 and specialises in 3D printing, CNC milling and laser cutting, but still
maintains his painting, drawing and printmaking practice.

Ali Napier is born and bred in Dundee and has worked at DJCAD since 2002, initially
supporting the Interaction and Product Design undergraduate programs. His background is
in music technology and IT, as well as Latin languages. He was one of the group that initially
pushed for DJCADMake to become a reality.

Ali leads support for microcontroller and interactive technologies in DJCAD.

**Comment by Saallen** [comment]
![ali rob](https://cloud.githubusercontent.com/assets/10194015/16596312/3f91701c-42eb-11e6-8a87-43892d110b2e.jpeg)

**Comment by thornet** [comment]
<3
